
# html lang
language: zh-cmn-Hans

# main menu navigation
menu:
  Home: /
  Archives: /blog/archives
  About: /blog/about

excerpt: true

# feed
atom: /atom.xml

# Miscelaneous
favicon: /img/favicon.png

# 百度统计
baidu_tongji_id: 

# uyan 评论系统
uyan_id: 
